Add ZAP Scan job

diff --git a/.github/workflows/devsecops-pipeline.yml b/.github/workflows/devsecops-pipeline.yml
--- a/.github/workflows/devsecops-pipeline.yml
+++ b/.github/workflows/devsecops-pipeline.yml
@@ -120,3 +120,33 @@ jobs:
           format: table
           exit-code: "0"
           severity: HIGH,CRITICAL
+
+  zap-scan:
+    name: OWASP ZAP DAST Scan
+
+    runs-on: ubuntu-latest
+
+    needs: trivy-image
+
+    permissions:
+      contents: read
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
+
+      - name: Start DVWA
+        run: docker compose up -d
+
+      - name: Wait for DVWA
+        run: |
+          for i in {1..30}; do
+            if curl -s http://localhost:8080 > /dev/null; then
+              echo "DVWA is ready."
+              exit 0
+            fi
+            echo "Waiting..."
+            sleep 5
+          done
+          echo "DVWA failed to start."
+          exit 1
